/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./dist/**/*.{html,js}"],
  theme: {
    extend: {
      backgroundImage: {
        quintex: "url('/dist/assest/logo.png')",
        snniit: "url('/dist/assest/snnit.png')",
        venixx: "url('/dist/assest/venix.png')",
        paraIcon: "url('/dist/assest/para_icon.png')",
        zindexI: "url('/dist/assest/zindex.png')",
        parabolic: "url('/dist/assest/Parabolic.png')",
        pedmas: "url('/dist/assest/Pedmas.png')",
        mainImg: "url('/dist/assest/Rectangle.png')",
        buyingImg: "url('/dist/assest/buyingImg.png')",
        sellingImg: "url('/dist/assest/SellingImg.png')",
        consultionImg: "url('/dist/assest/consultationImg.png')",
        propertyImg: "url('/dist/assest/PropertyManagement.png')",
        downButton: "url('/dist/assest/downButton.png')",
        vectorLeft: "url('/dist/assest/VectorLeft.png')",
        vectorRight: "url('/dist/assest/VectorRight.png')",
        tape: "url('/dist/assest/arcticons_tapemeasure.png')",
        bath: "url('/dist/assest/teenyicons_bath-outline.png')",
        tape: "url('/dist/assest/arcticons_tapemeasure.png')",
        bed: "url('/dist/assest/ic_sharp-bed.png')",
        location: "url('/dist/assest/ion_location-outline.png')",
        firstImg: "url('/dist/assest/firstImg.png')",
        secondImg: "url('/dist/assest/secondImg.png')",
        thirdImg: "url('/dist/assest/thirdImg.png')",
        forthImg: "url('/dist/assest/forthImg.png')",
        fithImg: "url('/dist/assest/firstImg.png')",
        mrLeftImg: "url('/dist/assest/mrLeft.png')",
        madamImg: "url('/dist/assest/madam.png')",
        kilImg: "url('/dist/assest/kil.png')",
      },
    },
  },
  plugins: [],
};
